#!/bin/sh

case "$1" in
        start)
                printf "Starting PHP websocket server ... "
                /usr/bin/php /home/php/yeacreate/restart.php
                echo "done.start"
                ;;
        stop)
                printf "Stopping websocket server ..."
                /usr/bin/php /home/php/yeacreate/start.php stop;
                ps | grep 'WorkerMan' | grep -w 'yeacweboswebsocket' | grep -v grep | awk '{print $1}' | xargs kill -9;
                echo "done.stop"
                ;;
        restart)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "usage: $0 {start|stop|restart}"
                ;;
esac
exit 0
