#!/bin/sh

WCOMMAND="--tty=2"
#WCOMMAND="--tty=2 --idle-time=0"
CCOMMAND="--no-sandbox --disable-web-security --kiosk --user-data-dir --test-type --gpu-sandbox-start-early --ozone-platform=wayland --ignore-gpu-blacklist --incognito --disable-pinch --overscroll-history-navigation=0 --ignore-certificate-errors --force-device-scale-factor=2.5 --disk-cache-dir=/dev/null --disk-cache-size=1 --disable-popup-blocking --no-first-run --disable-desktop-notifications --disable-web-security  --use-fake-ui-for-media-stream /home/php/www/tabletweb/index.html"

case "$1" in
        start)
                printf "Starting chromium ... "
                mkdir -p /tmp/.xdg &&  chmod 0700 /tmp/.xdg;export XDG_RUNTIME_DIR=/tmp/.xdg;export WESTON_DRM_MIRROR=1;
                touch /dev/video-dec0;
                chmod 666 /dev/video-dec0;
                echo enc > /dev/video-enc0;
                chmod 666 /dev/video-enc0;
                amixer -q set DAC '100%';
                start-stop-daemon -S -q -m -b -p /tmp/weston.pid --exec /usr/bin/weston -- $WCOMMAND
                start-stop-daemon -S -q -m -b -p /tmp/chromium.pid --exec /usr/bin/chromium -- $CCOMMAND
                echo "done."
                ;;
        stop)
                printf "Stopping chromium ..."
                rm /tmp/.xdg/ -fr;
                start-stop-daemon -K -q -p /tmp/chromium.pid;
                start-stop-daemon -K -q -p /tmp/weston.pid;
                echo "done."
                ;;
        restart)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "usage: $0 {start|stop|restart}"
                ;;
esac
exit 0
